### ISSUE TITLE
yarn dev 에러

### ISSUE THREAD

**Issue by wiserain** [tarpha/torrssen#1]
환경은 ubuntu 18.04

![picpick_capture_20181031_001](https://user-images.githubusercontent.com/20354654/47737327-9c06a680-dcab-11e8-9cf9-22ecdf7dbb3b.png)

16.04에서는 잘 되는데... 혹시 코드 레벨에서 해결할 수 있는 에러라면 한번 살펴봐 주시기 바랍니다.

**Comment by tarpha** [comment]
말씀하신 환경에서 한번 테스트 해 보겠습니다.

2018년 10월 31일 (수) 오전 2:30, wiserain <notifications@github.com>님이 작성:

**Comment by tarpha** [comment]
ubuntu 18.04.1 에서 정상 동작 확인했습니다. (Docker 환경)
실행환경은 다음과 같습니다.
yarn 1.12.1
nodejs 11.0.0

초기 yarn을 통한 node module install 과정에서 에러가 발생하여 g++는 따로 설치하였습니다. (apt-get)

**Comment by wiserain** [comment]
구글링 해보니 3000번 기본 포트가 다른 앱에서 사용중이거나 이전 빌드에서 점유중이라는듯 합니다. 재부팅하면 해결될 것 같지만 그냥 docker 환경으로....

그리고 포트가 바뀌면 빌드를 다시 해야 적용이 됩니다. 직접 해보고 알아낸건데 맞겠죠?

**Comment by tarpha** [comment]
포트정보는 .env에서 빌드 없이 되야 하는데 확인 좀 해보겠습니다. 

말씀하신 프록시는 적용해보도록 하겠습니다. 

아 전 도커 리눅스로 alpine 사용 중입니다. 가벼워서 좋습니다.

**Comment by wiserain** [comment]
네 저도 최종 목표는 도커로 하는거라 별도 컨테이너를 구성할지 어떻게 할지 고민 중이고 그에 따라 테스트해보고 있습니다.

**Comment by tarpha** [comment]
말씀하신 port 변경이 yarn dev에서 front 단이 3000으로 고정되는 것을 확인하였습니다. 
몇가지 방법을 써봤는데 잘 안되네요. 

다른 방법을 찾아보겠습니다.

**Comment by tarpha** [comment]
실행 시 dotenv를 로드하도록 package,json의 실행 옵션을 바꿨습니다.
이제 .env 상의 PORT로 개발/운영 모두 정상 동작합니다.

**Comment by sangwon1214** [comment]
Administrator@sw MINGW64 ~/Desktop/nextjs--sangwon/nextjs--sangwon (main)
$ yarn dev
yarn run v1.22.22
error Couldn't find a package.json file in "C:\\Users\\Administrator\\Desktop\\nextjs--sangwon\\nextjs--sangwon"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Administrator@sw MINGW64 ~/Desktop/nextjs--sangwon/nextjs--sangwon (main)
$ yarn dev
yarn run v1.22.22


이런식으로 코드가 뜹니다 .. 혹시 아시는 분있으실까요 ?? 도움 좀 부탁드립니다
