### ISSUE TITLE
https proxy 뒤의 transmission 연동

### ISSUE THREAD

**Issue by wiserain** [tarpha/torrssen#2]
방법을 알아내서 남깁니다.

host는 https:// 없이 abc.domain.com만
port는 443
ssl: true로 해줘야 하더군요.

언제 시간 되시면 ssl도 .env 안에서 컨트롤 할 수 있게 빼주시면 감사하겠습니다.

**Comment by tarpha** [comment]
프록시를 사용 안했어서 몰랐군요. 

사실 사용은 하지만 내부에서는 그냥 패스하고 

시놀로지 리버스 프록시로 https로 넘기고 있습니다. 

말씀하신 ssl 옵션 넣겠습니다.

**Comment by wiserain** [comment]
프록시 얘기가 나와서 여기 이슈에 달아봅니다. 

저는 하나의 컨테이너에 flexget과 transmission을 같이 넣고 트랜스미션은 root에서 redirect로 /transmission/rpc에 전달되게, flexget의 webui는 /flexget의 location 인자를 받아서 프록싱하게 해서 씁니다.

여기에 /webui로 이 프로젝트를 같이 올릴까 싶어서 테스트해봤는데 제가 아는 문제해결방법으로는 다 실패했습니다. 말씀하신대로 시놀로지 리버스 프록시로 넘길때는 서브도메인 루트로 매핑하시는거죠? 예를 들어 https://abc.domain.com/webui 이런식으로는 테스트 해보셨는지요?

질문이 많네요. 감사합니다.

**Comment by tarpha** [comment]
서브도메인은 명시하지 않고 포트 정보만 넣어서 사용합니다. 제 용도는 트렌스미션이 https를 지원하지 않아 사용하지요. 

말씀하신 서브 도메인을 같이 사용하는 방식은 한번 찾아보겠습니다. 

각기 다른 웹서버의 포트를 하나로 묶는 작업이 필요할거 같은데 nginx나 apache 옵션을 봐야겠네요.

질문은 편하게 해주세요. 제가 도움 받은 부분이 더 많습니다.
