### ISSUE TITLE
기능 요청 - rss source

### ISSUE THREAD

**Issue by wiserain** [tarpha/torrssen#4]
1. list of rss 가능하게...

.env를 통해서
```
...
RSSURL1=이름 / 주소
RSSURL2=이름 / 주소
...
```

그리고 드롭 다운이나 스와이프 기타 선택 메뉴를 통해서 해당 RSS만 탐색 가능하도록...

2. search rss 가능하게... (flexget과 유사한 기능)

보통 rss 파싱 주소가 rss.domain.com/rss.php?bid=xxx&keyword=abc 이런식인데 최상단의 검색바에서 검색하면 search rss를 통해서 결과를 탐색하고 tramission에 던질 수 있도록...

제게 필요한 기능이라 정리해서 남겨봅니다. 감사합니다.

**Comment by tarpha** [comment]
답이 늦었네요. 죄송합니다. 왼팔을 좀 다쳐서 고치고 진행하고 피드백 드릴께요.

**Comment by wiserain** [comment]
@tarpha 뭘..요. 몸조리 잘하세요. 급한거 아니랍니다.

**Comment by tarpha** [comment]
많이 늦었네요. 말씀하신 기능 추가하였습니다.
sqlite DB를 추가하였으며, 파일 및 스키마는 자동으로 생성합니다.
설정 페이지는 주소:포트/setting 으로 접속하시면 설정 가능합니다.

추가로 요즘 새로운 모듈들이 많이 올라와서 아얘 싹 개편을 계획하고 있습니다.
